# Generated by Django 2.0.13 on 2020-09-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US_Stock',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('highvalue', models.FloatField()),
                ('lowvalue', models.FloatField()),
                ('openvalue', models.FloatField()),
                ('closevalue', models.FloatField()),
                ('volumevalue', models.FloatField()),
                ('adjclosevalue', models.FloatField()),
            ],
        ),
    ]
